import { JSONPath } from "jsonpath-plus";
import { DataType, PathInfo } from "../types";

/**
 * Extracts all paths from a JSON object
 */
export function extractPaths(
  json: any,
  parentPath: string = "$",
  options: { optimizeArrays?: boolean } = { optimizeArrays: true },
): PathInfo[] {
  if (json === null || json === undefined) {
    return [{ path: parentPath, type: "null", value: null }];
  }

  const type = getDataType(json);

  if (type === "object") {
    const paths: PathInfo[] = [];

    // Add the object itself
    paths.push({ path: parentPath, type, value: json });

    // Add all properties
    for (const key in json) {
      const childPath = `${parentPath}['${key}']`;
      paths.push(...extractPaths(json[key], childPath, options));
    }

    return paths;
  } else if (type === "array") {
    const paths: PathInfo[] = [];

    // Add the array itself
    paths.push({ path: parentPath, type, value: json });

    if (options.optimizeArrays && json.length > 0) {
      // Only process the first item of the array and use [*] notation for subsequent operations
      const firstItem = json[0];
      const childPath = `${parentPath}[*]`;

      // Use [0] internally for the first item but present it as [*] in the path
      const firstItemPaths = extractPaths(
        firstItem,
        `${parentPath}[0]`,
        options,
      );

      // Replace all [0] with [*] in the paths
      const wildcardPaths = firstItemPaths.map((pathInfo) => ({
        ...pathInfo,
        path: pathInfo.path.replace(`${parentPath}[0]`, childPath),
      }));

      paths.push(...wildcardPaths);

      // Add an indicator to differentiate between actual array items and wildcards
      return paths;
    } else {
      // Original behavior - process each array item individually
      json.forEach((item: any, index: number) => {
        const childPath = `${parentPath}[${index}]`;
        paths.push(...extractPaths(item, childPath, options));
      });

      return paths;
    }
  } else {
    // Primitive value
    return [{ path: parentPath, type, value: json }];
  }
}

/**
 * Gets the data type of a value
 */
export function getDataType(value: any): DataType {
  if (value === null) return "null";
  if (Array.isArray(value)) return "array";

  const type = typeof value;

  if (type === "string") return "string";
  if (type === "number") return "number";
  if (type === "boolean") return "boolean";
  if (type === "object") return "object";

  return "unknown";
}

/**
 * Parses a JSONPath string into an array of keys/indices.
 * Handles formats like $['key']['subKey'] or $[0]['name'] or $[*]['name']
 * Does NOT handle complex JSONPath features like filters, etc.
 * This needs to match the paths generated by extractPaths.
 */
export function parseJsonPathSegments(path: string): (string | number | "*")[] {
  if (!path || typeof path !== "string" || path === "$") {
    return [];
  }

  // Remove leading '$'
  const normalizedPath = path.startsWith("$.")
    ? path.substring(2)
    : path.startsWith("$[")
      ? path.substring(1)
      : path.startsWith("$")
        ? path.substring(1)
        : path;

  // Regex to match ['key'] or [index] or [*]
  const segments: (string | number | "*")[] = [];
  const regex = /\['([^']+?)'\]|\[(\d+)\]|\[(\*)\]|\.?([^.\[\]]+)/g;
  let match;

  while ((match = regex.exec(normalizedPath)) !== null) {
    if (match[1]) {
      // Quoted key: ['key']
      segments.push(match[1]);
    } else if (match[2]) {
      // Array index: [0]
      segments.push(parseInt(match[2], 10));
    } else if (match[3]) {
      // Wildcard: [*]
      segments.push("*");
    } else if (match[4]) {
      // Dot notation key: .key
      segments.push(match[4]);
    }
  }
  return segments;
}

export function getValueByPath(json: any, path: string): any {
  if (path === "$" || !path) return json;

  // For paths with wildcards, use the JSONPath library
  if (path.includes("[*]")) {
    try {
      // Convert our [*] to JSONPath's [*] syntax
      const jsonPathQuery = path;
      const result = JSONPath({ path: jsonPathQuery, json, wrap: false });
      return result;
    } catch (error) {
      console.error(`Error using JSONPath for wildcard path: ${path}`, error);
      return undefined;
    }
  }

  // For standard paths, use direct property access for better performance
  try {
    const segments = parseJsonPathSegments(path);
    let current = json;
    for (const segment of segments) {
      if (
        current === null ||
        typeof current !== "object" ||
        !Object.prototype.hasOwnProperty.call(current, segment)
      ) {
        return undefined;
      }
      current = current[segment as string | number];
    }
    return current;
  } catch (error) {
    // Fallback to JSONPath if direct access fails
    try {
      const result = JSONPath({ path, json, wrap: false });
      return result;
    } catch (jsonPathError) {
      console.error(`Failed to get value by path ${path}:`, jsonPathError);
      return undefined;
    }
  }
}

export function setValueByPath(obj: any, path: string, value: any): void {
  if (path === "$" || !path) {
    if (path === "$") {
      console.error(
        "setValueByPath: Root path '$' cannot be set directly. Modify the object reference instead.",
      );
      throw new Error(
        "setValueByPath: Root path '$' is ambiguous. The target object itself should be modified or replaced by the caller if the entire structure changes.",
      );
    }
    console.error(`setValueByPath: Path is empty or invalid: "${path}"`);
    return;
  }

  // Handle wildcard paths
  if (path.includes("[*]")) {
    const segments = parseJsonPathSegments(path);
    let current = obj;
    let wildcardFound = false;
    let wildcardIndex = -1;

    // Find the first wildcard in the path
    for (let i = 0; i < segments.length; i++) {
      if (segments[i] === "*") {
        wildcardFound = true;
        wildcardIndex = i;
        break;
      }
    }

    if (wildcardFound) {
      // Navigate to the parent of the wildcard
      for (let i = 0; i < wildcardIndex; i++) {
        const segment = segments[i];
        if (
          current === null ||
          (typeof current !== "object" && !Array.isArray(current))
        ) {
          throw new Error(
            `Cannot navigate to parent of wildcard in path: ${path}`,
          );
        }

        if (!Object.prototype.hasOwnProperty.call(current, segment)) {
          current[segment as string | number] =
            typeof segments[i + 1] === "number" || segments[i + 1] === "*"
              ? []
              : {};
        }

        current = current[segment as string | number];
      }

      // Apply the value to all array items
      if (Array.isArray(current)) {
        const remainingSegments = segments.slice(wildcardIndex + 1);

        for (let i = 0; i < current.length; i++) {
          let arrayItem = current[i];

          // Navigate through the remaining path for each array item
          for (let j = 0; j < remainingSegments.length - 1; j++) {
            const segment = remainingSegments[j];

            if (
              arrayItem === null ||
              (typeof arrayItem !== "object" && !Array.isArray(arrayItem))
            ) {
              arrayItem =
                typeof remainingSegments[j + 1] === "number" ||
                remainingSegments[j + 1] === "*"
                  ? []
                  : {};
              current[i] = arrayItem;
            }

            if (!Object.prototype.hasOwnProperty.call(arrayItem, segment)) {
              arrayItem[segment as string | number] =
                typeof remainingSegments[j + 1] === "number" ||
                remainingSegments[j + 1] === "*"
                  ? []
                  : {};
            }

            arrayItem = arrayItem[segment as string | number];
          }

          // Set the value on the last segment
          if (remainingSegments.length > 0) {
            const lastSegment = remainingSegments[remainingSegments.length - 1];
            if (
              arrayItem !== null &&
              (typeof arrayItem === "object" || Array.isArray(arrayItem))
            ) {
              arrayItem[lastSegment as string | number] = value;
            }
          } else {
            // If there are no remaining segments, replace the entire array item
            current[i] = value;
          }
        }
      } else {
        console.error(`Expected array at wildcard position in path: ${path}`);
      }

      return;
    }
  }

  // Standard path handling (unchanged)
  const segments = parseJsonPathSegments(path);
  if (segments.length === 0) {
    console.error(
      `setValueByPath: Could not parse path into segments or path is invalid: "${path}"`,
    );
    throw new Error(`Invalid path for setValueByPath: ${path}`);
  }

  let current = obj;

  for (let i = 0; i < segments.length - 1; i++) {
    const segment = segments[i];
    const nextSegment = segments[i + 1];

    if (
      current === null ||
      (typeof current !== "object" && !Array.isArray(current))
    ) {
      console.error(
        `setValueByPath: Cannot create property on non-object/array. Path: "${path}", Segment: "${String(segment)}"`,
      );
      throw new Error(
        `Parent structure traversal error for path: ${path} (segment: ${String(segment)})`,
      );
    }

    const currentSegmentValue = current[segment as string | number];

    if (
      !Object.prototype.hasOwnProperty.call(current, segment) ||
      currentSegmentValue === null ||
      typeof currentSegmentValue !== "object"
    ) {
      current[segment as string | number] =
        typeof nextSegment === "number" || nextSegment === "*" ? [] : {};
    }
    current = current[segment as string | number];
    if (current === undefined) {
      console.error(
        `setValueByPath: 'current' became undefined after accessing/creating segment "${String(segment)}" for path "${path}"`,
      );
      throw new Error(
        `Path creation failed unexpectedly at segment "${String(segment)}" for path "${path}"`,
      );
    }
  }

  const lastSegment = segments[segments.length - 1];
  if (
    current === null ||
    (typeof current !== "object" && !Array.isArray(current))
  ) {
    console.error(
      `setValueByPath: Final parent segment is not an object/array. Path: "${path}", Last Segment: "${String(lastSegment)}"`,
    );
    throw new Error(
      `Final parent not found for path: ${path} (last segment: ${String(lastSegment)})`,
    );
  }

  if (Array.isArray(current) && typeof lastSegment === "number") {
    while (current.length <= lastSegment) {
      current.push(undefined);
    }
  }

  current[lastSegment as string | number] = value;
}

/**
 * Validates if a string is valid JSON
 */
export function isValidJson(str: string): boolean {
  try {
    JSON.parse(str);
    return true;
  } catch (error) {
    return false;
  }
}

/**
 * Formats a JSON string with proper indentation
 */
export function formatJson(json: string): string {
  try {
    const parsed = JSON.parse(json);
    return JSON.stringify(parsed, null, 2);
  } catch (error) {
    return json;
  }
}

/**
 * Converts a JSONPath to a human-readable path
 * e.g. $['user']['name'] -> user.name
 */
export function jsonPathToReadablePath(path: string): string {
  if (!path || path === "$") return "root";
  // $['user']['items'][0]['name'] -> user.items[0].name
  return path
    .replace(/^\$\.?/, "") // Remove leading $ or $.
    .replace(/\[\'([^']+?)\'\]/g, ".$1") // ['key'] -> .key
    .replace(/\[(\d+)\]/g, "[$1]") // [0]   -> [0]
    .replace(/^\./, ""); // Remove leading dot if any
}

/**
 * Converts a human-readable path to a JSONPath
 * e.g. user.name -> $['user']['name']
 */
export function readablePathToJsonPath(path: string): string {
  if (!path) return "$";
  return `$.${path.replace(/\[(\d+)\]/g, ".[$1]")}`; // user[0] -> user.[0] -> then split by .
}
