import { JSONPath } from 'jsonpath-plus';
import { DataType, PathInfo } from '../types';

/**
 * Extracts all paths from a JSON object
 */
export function extractPaths(json: any, parentPath: string = '$'): PathInfo[] {
  if (json === null || json === undefined) {
    return [{ path: parentPath, type: 'null', value: null }];
  }

  const type = getDataType(json);
  
  if (type === 'object') {
    const paths: PathInfo[] = [];
    
    // Add the object itself
    paths.push({ path: parentPath, type, value: json });
    
    // Add all properties
    for (const key in json) {
      const childPath = `${parentPath}['${key}']`;
      paths.push(...extractPaths(json[key], childPath));
    }
    
    return paths;
  } else if (type === 'array') {
    const paths: PathInfo[] = [];
    
    // Add the array itself
    paths.push({ path: parentPath, type, value: json });
    
    // Add all elements
    json.forEach((item: any, index: number) => {
      const childPath = `${parentPath}[${index}]`;
      paths.push(...extractPaths(item, childPath));
    });
    
    return paths;
  } else {
    // Primitive value
    return [{ path: parentPath, type, value: json }];
  }
}

/**
 * Gets the data type of a value
 */
export function getDataType(value: any): DataType {
  if (value === null) return 'null';
  if (Array.isArray(value)) return 'array';
  
  const type = typeof value;
  
  if (type === 'string') return 'string';
  if (type === 'number') return 'number';
  if (type === 'boolean') return 'boolean';
  if (type === 'object') return 'object';
  
  return 'unknown';
}

/**
 * Parses a JSONPath string into an array of keys/indices.
 * Handles formats like $['key']['subKey'] or $[0]['name']
 * Does NOT handle complex JSONPath features like wildcards, filters, etc.
 * This needs to match the paths generated by extractPaths.
 */
export function parseJsonPathSegments(path: string): (string | number)[] {
  if (!path || typeof path !== 'string' || path === '$') {
    return [];
  }

  // Remove leading '$'
  const normalizedPath = path.startsWith('$.') ? path.substring(2) :
                         path.startsWith('$[') ? path.substring(1) :
                         path.startsWith('$') ? path.substring(1) : path;

  // Regex to match ['key'] or [index]
  const segments: (string | number)[] = [];
  const regex = /\['([^']+?)'\]|\[(\d+)\]|\.?([^.\[\]]+)/g;
  let match;

  while ((match = regex.exec(normalizedPath)) !== null) {
    if (match[1]) { // Quoted key: ['key']
      segments.push(match[1]);
    } else if (match[2]) { // Array index: [0]
      segments.push(parseInt(match[2], 10));
    } else if (match[3]) { // Dot notation key: .key
      segments.push(match[3]);
    }
  }
  return segments;
}


export function getValueByPath(json: any, path: string): any {
  if (path === '$' || !path) return json;

  // Using JSONPath library for robust getting
  try {
    const result = JSONPath({ path, json, wrap: false }); // wrap: false to get raw value
    return result; // JSONPath might return an array of matches; often we want the first or only.
                   // If path guarantees a single value, result[0] is fine, but handle multiple matches if paths can be broad.
                   // For simple paths, it usually returns the value directly if wrap:false.
                   // If JSONPath returns an array even for single matches:
                   // return result !== undefined && result.length > 0 ? result[0] : undefined;
  } catch (error) {
    // Fallback to manual parsing for simple cases or if JSONPath fails unexpectedly
    const segments = parseJsonPathSegments(path);
    let current = json;
    for (const segment of segments) {
      if (current === null || typeof current !== 'object' || !Object.prototype.hasOwnProperty.call(current, segment)) {
        return undefined;
      }
      current = current[segment as string | number];
    }
    return current;
  }
}

export function setValueByPath(obj: any, path: string, value: any): void {
  if (path === '$' || !path) {
    if (path === '$') {
        console.error("setValueByPath: Root path '$' cannot be set directly. Modify the object reference instead.");
        throw new Error("setValueByPath: Root path '$' is ambiguous. The target object itself should be modified or replaced by the caller if the entire structure changes.");
    }
    console.error(`setValueByPath: Path is empty or invalid: "${path}"`);
    return;
  }

  const segments = parseJsonPathSegments(path);
  if (segments.length === 0) { // path was not '$' but segments are empty (e.g. "$.")
      console.error(`setValueByPath: Could not parse path into segments or path is invalid: "${path}"`);
      throw new Error(`Invalid path for setValueByPath: ${path}`);
  }

  let current = obj;

  for (let i = 0; i < segments.length - 1; i++) {
    const segment = segments[i];
    const nextSegment = segments[i + 1];

    if (current === null || (typeof current !== 'object' && !Array.isArray(current))) {
      console.error(`setValueByPath: Cannot create property on non-object/array. Path: "${path}", Segment: "${String(segment)}"`);
      throw new Error(`Parent structure traversal error for path: ${path} (segment: ${String(segment)})`);
    }

    const currentSegmentValue = current[segment as string | number];

    if (!Object.prototype.hasOwnProperty.call(current, segment) || currentSegmentValue === null || typeof currentSegmentValue !== 'object') {
      current[segment as string | number] = (typeof nextSegment === 'number') ? [] : {};
    }
    current = current[segment as string | number];
     if (current === undefined) { // Should not happen if creation logic is correct
        console.error(`setValueByPath: 'current' became undefined after accessing/creating segment "${String(segment)}" for path "${path}"`);
        throw new Error(`Path creation failed unexpectedly at segment "${String(segment)}" for path "${path}"`);
    }
  }

  const lastSegment = segments[segments.length - 1];
   if (current === null || (typeof current !== 'object' && !Array.isArray(current))) {
      console.error(`setValueByPath: Final parent segment is not an object/array. Path: "${path}", Last Segment: "${String(lastSegment)}"`);
      throw new Error(`Final parent not found for path: ${path} (last segment: ${String(lastSegment)})`);
  }

  if (Array.isArray(current) && typeof lastSegment === 'number') {
    while (current.length <= lastSegment) {
      current.push(undefined);
    }
  }

  current[lastSegment as string | number] = value;
}

/**
 * Validates if a string is valid JSON
 */
export function isValidJson(str: string): boolean {
  try {
    JSON.parse(str);
    return true;
  } catch (error) {
    return false;
  }
}

/**
 * Formats a JSON string with proper indentation
 */
export function formatJson(json: string): string {
  try {
    const parsed = JSON.parse(json);
    return JSON.stringify(parsed, null, 2);
  } catch (error) {
    return json;
  }
}

/**
 * Converts a JSONPath to a human-readable path
 * e.g. $['user']['name'] -> user.name
 */
 export function jsonPathToReadablePath(path: string): string {
   if (!path || path === '$') return 'root';
   // $['user']['items'][0]['name'] -> user.items[0].name
   return path
     .replace(/^\$\.?/, '') // Remove leading $ or $.
     .replace(/\[\'([^']+?)\'\]/g, '.$1') // ['key'] -> .key
     .replace(/\[(\d+)\]/g, '[$1]')      // [0]   -> [0]
     .replace(/^\./, '');                // Remove leading dot if any
 }

/**
 * Converts a human-readable path to a JSONPath
 * e.g. user.name -> $['user']['name']
 */
export function readablePathToJsonPath(path: string): string {
  if (!path) return '$';
  return `$.${path.replace(/\[(\d+)\]/g, '.[$1]')}`; // user[0] -> user.[0] -> then split by .
}