// Mock implementation of monaco-editor for Jest tests
const monaco = {
  editor: {
    create: jest.fn(() => ({
      getValue: jest.fn(() => ''),
      setValue: jest.fn(),
      getModel: jest.fn(() => null),
      setModel: jest.fn(),
      dispose: jest.fn(),
      onDidChangeModelContent: jest.fn(() => ({ dispose: jest.fn() })),
      focus: jest.fn(),
      layout: jest.fn(),
      getAction: jest.fn(),
      trigger: jest.fn(),
      addCommand: jest.fn(),
      createContextKey: jest.fn(() => ({
        set: jest.fn(),
        get: jest.fn(),
        reset: jest.fn()
      })),
      onDidBlurEditorWidget: jest.fn(() => ({ dispose: jest.fn() })),
      onDidFocusEditorWidget: jest.fn(() => ({ dispose: jest.fn() })),
      onKeyDown: jest.fn(() => ({ dispose: jest.fn() })),
      onKeyUp: jest.fn(() => ({ dispose: jest.fn() })),
      onDidChangeCursorPosition: jest.fn(() => ({ dispose: jest.fn() })),
      onDidChangeModelLanguage: jest.fn(() => ({ dispose: jest.fn() })),
      onDidChangeModelLanguageConfiguration: jest.fn(() => ({ dispose: jest.fn() })),
      onDidChangeConfiguration: jest.fn(() => ({ dispose: jest.fn() })),
      onDidChangeModel: jest.fn(() => ({ dispose: jest.fn() })),
      onDidChangeModelContent: jest.fn(() => ({ dispose: jest.fn() })),
      onDidChangeModelOptions: jest.fn(() => ({ dispose: jest.fn() })),
      onDidChangeModelDecorations: jest.fn(() => ({ dispose: jest.fn() })),
      onDidChangeModelTokens: jest.fn(() => ({ dispose: jest.fn() })),
      onDidChangeModelLanguageTokens: jest.fn(() => ({ dispose: jest.fn() })),
      onDidChangeModelDecorations: jest.fn(() => ({ dispose: jest.fn() })),
      onDidChangeModelTokens: jest.fn(() => ({ dispose: jest.fn() })),
      onDidChangeModelLanguageTokens: jest.fn(() => ({ dispose: jest.fn() })),
      onDidChangeModelDecorations: jest.fn(() => ({ dispose: jest.fn() })),
      onDidChangeModelTokens: jest.fn(() => ({ dispose: jest.fn() })),
      onDidChangeModelLanguageTokens: jest.fn(() => ({ dispose: jest.fn() })),
      onDidChangeModelDecorations: jest.fn(() => ({ dispose: jest.fn() })),
      onDidChangeModelTokens: jest.fn(() => ({ dispose: jest.fn() })),
      onDidChangeModelLanguageTokens: jest.fn(() => ({ dispose: jest.fn() }))
    })),
    createModel: jest.fn(() => ({
      getValue: jest.fn(() => ''),
      setValue: jest.fn(),
      dispose: jest.fn(),
      onDidChangeContent: jest.fn(() => ({ dispose: jest.fn() })),
      getLinesContent: jest.fn(() => []),
      getLineCount: jest.fn(() => 0),
      getLineContent: jest.fn(() => ''),
      getLanguageId: jest.fn(() => 'plaintext'),
      updateOptions: jest.fn(),
      pushUndoStop: jest.fn(),
      pushEditOperations: jest.fn(),
      setEOL: jest.fn(),
      getEOL: jest.fn(() => '\n'),
      getValueInRange: jest.fn(() => ''),
      getLineFirstNonWhitespaceColumn: jest.fn(() => 1),
      getLineLastNonWhitespaceColumn: jest.fn(() => 1),
      getLineMaxColumn: jest.fn(() => 1),
      getLineMinColumn: jest.fn(() => 1),
      getOffsetAt: jest.fn(() => 0),
      getPositionAt: jest.fn(() => ({ lineNumber: 1, column: 1 })),
      getWordAtPosition: jest.fn(() => null),
      getWordUntilPosition: jest.fn(() => ({ word: '', startColumn: 1, endColumn: 1 })),
      isDisposed: jest.fn(() => false),
      findMatches: jest.fn(() => []),
      findNextMatch: jest.fn(() => null),
      findPreviousMatch: jest.fn(() => null),
      getModeId: jest.fn(() => 'plaintext'),
      getVersionId: jest.fn(() => 1),
      getAlternativeVersionId: jest.fn(() => 1),
      normalizeIndentation: jest.fn(() => ''),
      getDecorations: jest.fn(() => []),
      getDecorationsInRange: jest.fn(() => []),
      getLineDecorations: jest.fn(() => []),
      getLinesDecorations: jest.fn(() => []),
      getOverviewRulerDecorations: jest.fn(() => []),
      getAllDecorations: jest.fn(() => []),
      deltaDecorations: jest.fn(() => []),
      getOptions: jest.fn(() => ({})),
      detectIndentation: jest.fn(),
      normalizeIndentation: jest.fn(() => ''),
      getIndentationAtPosition: jest.fn(() => ''),
      getFormattingOptions: jest.fn(() => ({})),
      validatePosition: jest.fn(() => ({ lineNumber: 1, column: 1 })),
      modifyPosition: jest.fn(() => ({ lineNumber: 1, column: 1 })),
      validateRange: jest.fn(() => ({ startLineNumber: 1, startColumn: 1, endLineNumber: 1, endColumn: 1 })),
      getValueLength: jest.fn(() => 0),
      getFullModelRange: jest.fn(() => ({ startLineNumber: 1, startColumn: 1, endLineNumber: 1, endColumn: 1 })),
      isAttachedToEditor: jest.fn(() => false),
      id: 'mock-model'
    })),
    setModelLanguage: jest.fn(),
    getModelLanguage: jest.fn(() => 'plaintext'),
    getModels: jest.fn(() => []),
    getModel: jest.fn(() => null),
    onDidCreateModel: jest.fn(() => ({ dispose: jest.fn() })),
    onWillDisposeModel: jest.fn(() => ({ dispose: jest.fn() })),
    onDidChangeModelLanguage: jest.fn(() => ({ dispose: jest.fn() })),
    setTheme: jest.fn(),
    defineTheme: jest.fn(),
    remeasureFonts: jest.fn(),
    colorize: jest.fn(() => Promise.resolve('')),
    colorizeElement: jest.fn(() => Promise.resolve()),
    colorizeModelLine: jest.fn(() => ''),
    tokenize: jest.fn(() => []),
    setModelMarkers: jest.fn(),
    getModelMarkers: jest.fn(() => []),
    removeAllMarkers: jest.fn(),
    onDidChangeMarkers: jest.fn(() => ({ dispose: jest.fn() })),
    registerReferenceProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerRenameProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerSignatureHelpProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerHoverProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerDocumentSymbolProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerDocumentHighlightProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerDefinitionProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerImplementationProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerTypeDefinitionProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerCodeLensProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerCodeActionProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerDocumentFormattingEditProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerDocumentRangeFormattingEditProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerOnTypeFormattingEditProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerLinkProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerColorProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerFoldingRangeProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerDeclarationProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerSelectionRangeProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerDocumentSemanticTokensProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerDocumentRangeSemanticTokensProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerCompletionItemProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerInlineCompletionsProvider: jest.fn(() => ({ dispose: jest.fn() }))
  },
  languages: {
    register: jest.fn(),
    getLanguages: jest.fn(() => []),
    getEncodedLanguageId: jest.fn(() => 0),
    onLanguage: jest.fn(() => ({ dispose: jest.fn() })),
    setLanguageConfiguration: jest.fn(),
    setMonarchTokensProvider: jest.fn(),
    registerReferenceProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerRenameProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerSignatureHelpProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerHoverProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerDocumentSymbolProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerDocumentHighlightProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerDefinitionProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerImplementationProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerTypeDefinitionProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerCodeLensProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerCodeActionProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerDocumentFormattingEditProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerDocumentRangeFormattingEditProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerOnTypeFormattingEditProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerLinkProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerColorProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerFoldingRangeProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerDeclarationProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerSelectionRangeProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerDocumentSemanticTokensProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerDocumentRangeSemanticTokensProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerCompletionItemProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerInlineCompletionsProvider: jest.fn(() => ({ dispose: jest.fn() })),
    registerTokensProvider: jest.fn(() => ({ dispose: jest.fn() })),
    setTokensProvider: jest.fn(() => ({ dispose: jest.fn() })),
    setColorMap: jest.fn(),
    createMonacoLanguagesAPI: jest.fn(() => ({}))
  },
  Uri: {
    parse: jest.fn(() => ({ toString: jest.fn(() => 'mock-uri') })),
    file: jest.fn(() => ({ toString: jest.fn(() => 'mock-file-uri') })),
    from: jest.fn(() => ({ toString: jest.fn(() => 'mock-from-uri') })),
    joinPath: jest.fn(() => ({ toString: jest.fn(() => 'mock-join-path-uri') })),
    revive: jest.fn(() => ({ toString: jest.fn(() => 'mock-revive-uri') }))
  },
  Range: jest.fn(() => ({
    startLineNumber: 1,
    startColumn: 1,
    endLineNumber: 1,
    endColumn: 1
  })),
  Selection: jest.fn(() => ({
    startLineNumber: 1,
    startColumn: 1,
    endLineNumber: 1,
    endColumn: 1,
    selectionStartLineNumber: 1,
    selectionStartColumn: 1,
    positionLineNumber: 1,
    positionColumn: 1
  })),
  Position: jest.fn(() => ({
    lineNumber: 1,
    column: 1
  })),
  KeyCode: {},
  KeyMod: {},
  MarkerSeverity: {
    Hint: 1,
    Info: 2,
    Warning: 4,
    Error: 8
  },
  MarkerTag: {},
  CancellationToken: {
    None: {
      isCancellationRequested: false,
      onCancellationRequested: jest.fn(() => ({ dispose: jest.fn() }))
    }
  }
};

module.exports = monaco;
module.exports.default = monaco; 