import { DEFAULT_REMEDIATION } from "../constants";
import { SecretRule } from "../types";

export const providerRules: SecretRule[] = [
  {
    id: "aws-access-key-id",
    name: "AWS access key ID",
    provider: "AWS",
    severity: "high",
    confidence: "high",
    reason: "provider-pattern",
    regex: /\b((?:AKIA|ASIA)[A-Z0-9]{16})\b/g,
    secretGroup: 1,
    explanation: "Matches the stable AWS access key ID format.",
  },
  {
    id: "aws-secret-access-key",
    name: "AWS secret access key",
    provider: "AWS",
    severity: "critical",
    confidence: "high",
    reason: "secret-name-context",
    regex: /\b(?:AWS_SECRET_ACCESS_KEY|aws_secret_access_key)\s*[:=]\s*["']?([A-Za-z0-9/+=]{40})["']?/gi,
    secretGroup: 1,
    explanation: "AWS secret access key assignment.",
  },
  {
    id: "github-token",
    name: "GitHub token",
    provider: "GitHub",
    severity: "critical",
    confidence: "high",
    reason: "provider-pattern",
    regex: /\b((?:ghp|gho|ghu|ghs|ghr|github_pat)_[A-Za-z0-9_]{20,255})\b/g,
    secretGroup: 1,
    explanation: "Matches GitHub personal, OAuth, app, or fine-grained token prefixes.",
  },
  {
    id: "gitlab-token",
    name: "GitLab token",
    provider: "GitLab",
    severity: "critical",
    confidence: "high",
    reason: "provider-pattern",
    regex: /\b((?:glpat|glptt|glcbt)-[A-Za-z0-9_\-]{20,100})\b/g,
    secretGroup: 1,
    explanation: "Matches GitLab personal, project, group, trigger, or CI token prefixes.",
  },
  {
    id: "openai-api-key",
    name: "OpenAI API key",
    provider: "OpenAI",
    severity: "critical",
    confidence: "high",
    reason: "provider-pattern",
    regex: /\b((?:sk|sess)-[A-Za-z0-9_\-]{20,200})\b/g,
    secretGroup: 1,
    explanation: "Matches common OpenAI secret key prefixes.",
  },
  {
    id: "anthropic-api-key",
    name: "Anthropic API key",
    provider: "Anthropic",
    severity: "critical",
    confidence: "high",
    reason: "provider-pattern",
    regex: /\b(sk-ant-[A-Za-z0-9_\-]{20,200})\b/g,
    secretGroup: 1,
    explanation: "Matches Anthropic API key prefixes.",
  },
  {
    id: "google-api-key",
    name: "Google API key",
    provider: "Google",
    severity: "high",
    confidence: "high",
    reason: "provider-pattern",
    regex: /\b(AIza[0-9A-Za-z_\-]{35})\b/g,
    secretGroup: 1,
    explanation: "Matches the Google API key format.",
  },
  {
    id: "google-oauth-token",
    name: "Google OAuth access token",
    provider: "Google",
    severity: "critical",
    confidence: "high",
    reason: "provider-pattern",
    regex: /\b(ya29\.[A-Za-z0-9_\-]{20,500})\b/g,
    secretGroup: 1,
    explanation: "Matches Google OAuth 2.0 access token prefixes.",
  },
  {
    id: "slack-token",
    name: "Slack token",
    provider: "Slack",
    severity: "critical",
    confidence: "high",
    reason: "provider-pattern",
    regex: /\b((?:xox[baprs]|xapp)-[A-Za-z0-9\-]{10,200})\b/g,
    secretGroup: 1,
    explanation: "Matches Slack bot, user, app, and refresh token prefixes.",
  },
  {
    id: "slack-webhook",
    name: "Slack webhook URL",
    provider: "Slack",
    severity: "critical",
    confidence: "high",
    reason: "provider-pattern",
    regex: /\b(https:\/\/hooks\.slack\.com\/services\/[A-Z0-9]+\/[A-Z0-9]+\/[A-Za-z0-9]+)\b/g,
    secretGroup: 1,
    explanation: "Matches Slack incoming webhook URLs.",
  },
  {
    id: "stripe-secret-key",
    name: "Stripe secret key",
    provider: "Stripe",
    severity: "critical",
    confidence: "high",
    reason: "provider-pattern",
    regex: /\b((?:sk|rk)_(?:live|test)_[A-Za-z0-9]{16,120})\b/g,
    secretGroup: 1,
    explanation: "Matches Stripe secret and restricted API keys.",
  },
  {
    id: "discord-webhook",
    name: "Discord webhook URL",
    provider: "Discord",
    severity: "critical",
    confidence: "high",
    reason: "provider-pattern",
    regex: /\b(https:\/\/discord(?:app)?\.com\/api\/webhooks\/\d{17,19}\/[A-Za-z0-9_\-]+)\b/g,
    secretGroup: 1,
    explanation: "Matches Discord webhook URLs, which can post directly into a channel.",
  },
  {
    id: "discord-bot-token",
    name: "Discord bot token",
    provider: "Discord",
    severity: "critical",
    confidence: "high",
    reason: "provider-pattern",
    regex: /\b([MN][A-Za-z0-9_-]{23,25}\.[A-Za-z0-9_-]{6}\.[A-Za-z0-9_-]{27})\b/g,
    secretGroup: 1,
    explanation: "Matches Discord bot or user token structure.",
  },
  {
    id: "npm-token",
    name: "npm access token",
    provider: "npm",
    severity: "critical",
    confidence: "high",
    reason: "provider-pattern",
    regex: /\b(npm_[A-Za-z0-9]{36,120})\b/g,
    secretGroup: 1,
    explanation: "Matches npm access token prefixes.",
  },
  {
    id: "cloudflare-token",
    name: "Cloudflare API token",
    provider: "Cloudflare",
    severity: "high",
    confidence: "medium",
    reason: "secret-name-context",
    regex: /\b(?:cloudflare[_\-]?(?:api[_\-]?)?(?:token|key)|cf[_\-]?token)\b\s*[:=]\s*["']?([A-Za-z0-9_\-]{30,120})["']?/gi,
    secretGroup: 1,
    explanation: "Cloudflare token-like value assigned to a Cloudflare secret name.",
  },
  {
    id: "sendgrid-token",
    name: "SendGrid API key",
    provider: "SendGrid",
    severity: "critical",
    confidence: "high",
    reason: "provider-pattern",
    regex: /\b(SG\.[A-Za-z0-9_\-]{16,}\.[A-Za-z0-9_\-]{16,})\b/g,
    secretGroup: 1,
    explanation: "Matches SendGrid API key structure.",
  },
  {
    id: "sentry-dsn",
    name: "Sentry DSN",
    provider: "Sentry",
    severity: "medium",
    confidence: "medium",
    reason: "provider-pattern",
    regex: /\b(https:\/\/[a-f0-9]{32}@[a-z0-9.\-]+\/\d+)\b/gi,
    secretGroup: 1,
    explanation: "Matches Sentry DSN values. These may expose project ingest endpoints.",
  },
  {
    id: "bearer-token",
    name: "Bearer token",
    provider: "HTTP",
    severity: "high",
    confidence: "medium",
    reason: "secret-name-context",
    regex: /\bAuthorization\s*:\s*Bearer\s+([A-Za-z0-9._~+/=\-]{24,500})\b/gi,
    secretGroup: 1,
    explanation: "Authorization header contains an opaque bearer credential.",
  },
  {
    id: "basic-auth-header",
    name: "Basic auth header",
    provider: "HTTP",
    severity: "high",
    confidence: "medium",
    reason: "secret-name-context",
    regex: /\bAuthorization\s*:\s*Basic\s+([A-Za-z0-9+/=]{12,300})\b/gi,
    secretGroup: 1,
    explanation: "Authorization header contains base64-encoded basic credentials.",
  },
  {
    id: "database-url",
    name: "Database URL with credentials",
    provider: "Database",
    severity: "critical",
    confidence: "high",
    reason: "credential-url",
    regex: /\b((?:postgres(?:ql)?|mysql|mongodb(?:\+srv)?|redis|rediss|elasticsearch):\/\/(?:[^:\s/@]+)?:[^@\s]+@[^\s"'`<>]+)\b/gi,
    secretGroup: 1,
    explanation: "Connection URL embeds username and password material.",
  },
];

export const providerRuleRemediation = DEFAULT_REMEDIATION;
