export interface CompactEmoji {
  c: string; // char
  n: string; // name
  s: string; // shortcode (without colons)
  k: string[]; // keywords
  t: boolean; // supportsTones
  cat: string; // category
}

export const emojiData: CompactEmoji[] = [
  // Smileys & Emotion
  { c: "😀", n: "grinning face", s: "grinning", k: ["face", "smile", "happy", "joy"], t: false, cat: "Smileys & Emotion" },
  { c: "😃", n: "grinning face with big eyes", s: "smiley", k: ["face", "happy", "joy", "haha"], t: false, cat: "Smileys & Emotion" },
  { c: "😄", n: "grinning face with smiling eyes", s: "smile", k: ["face", "happy", "joy", "funny", "haha", "laugh"], t: false, cat: "Smileys & Emotion" },
  { c: "😁", n: "beaming face with smiling eyes", s: "grin", k: ["face", "happy", "smile", "joy", "grin"], t: false, cat: "Smileys & Emotion" },
  { c: "😆", n: "grinning squinting face", s: "laughing", k: ["happy", "joy", "lol", "laughing", "satisfied"], t: false, cat: "Smileys & Emotion" },
  { c: "😅", n: "grinning face with sweat", s: "sweat_smile", k: ["face", "hot", "happy", "laugh", "sweat", "smile"], t: false, cat: "Smileys & Emotion" },
  { c: "🤣", n: "rolling on the floor laughing", s: "rofl", k: ["face", "rolling", "floor", "laughing", "lol", "haha"], t: false, cat: "Smileys & Emotion" },
  { c: "😂", n: "face with tears of joy", s: "joy", k: ["face", "cry", "tears", "weep", "happy", "haha", "laugh"], t: false, cat: "Smileys & Emotion" },
  { c: "🙂", n: "slightly smiling face", s: "slightly_smiling_face", k: ["face", "smile"], t: false, cat: "Smileys & Emotion" },
  { c: "🙃", n: "upside-down face", s: "upside_down_face", k: ["face", "silly", "goofy", "sarcastic"], t: false, cat: "Smileys & Emotion" },
  { c: "😉", n: "winking face", s: "wink", k: ["face", "happy", "mischievous", "secret", "wink"], t: false, cat: "Smileys & Emotion" },
  { c: "😊", n: "smiling face with smiling eyes", s: "blush", k: ["face", "smile", "happy", "proud", "blush", "flattered"], t: false, cat: "Smileys & Emotion" },
  { c: "😇", n: "smiling face with halo", s: "innocent", k: ["face", "angel", "heaven", "halo"], t: false, cat: "Smileys & Emotion" },
  { c: "😍", n: "smiling face with heart-eyes", s: "heart_eyes", k: ["face", "love", "like", "affection", "valentines", "infatuation"], t: false, cat: "Smileys & Emotion" },
  { c: "🤩", n: "star-struck", s: "star_struck", k: ["face", "eyes", "star", "wow", "amazed"], t: false, cat: "Smileys & Emotion" },
  { c: "😘", n: "face blowing a kiss", s: "kissing_heart", k: ["face", "love", "like", "affection", "valentines", "infatuation"], t: false, cat: "Smileys & Emotion" },
  { c: "😗", n: "kissing face", s: "kissing", k: ["face", "love", "valentines", "kiss"], t: false, cat: "Smileys & Emotion" },
  { c: "😚", n: "kissing face with closed eyes", s: "kissing_closed_eyes", k: ["face", "love", "affection", "kiss"], t: false, cat: "Smileys & Emotion" },
  { c: "😙", n: "kissing face with smiling eyes", s: "kissing_smiling_eyes", k: ["face", "affection", "kiss", "happy"], t: false, cat: "Smileys & Emotion" },
  { c: "😋", n: "face savoring food", s: "yum", k: ["face", "tongue", "eat", "delicious", "yum"], t: false, cat: "Smileys & Emotion" },
  { c: "😛", n: "face with tongue", s: "stuck_out_tongue", k: ["face", "prank", "childish", "playful"], t: false, cat: "Smileys & Emotion" },
  { c: "😜", n: "winking face with tongue", s: "stuck_out_tongue_winking_eye", k: ["face", "prank", "silly", "goofy", "mischievous", "playful"], t: false, cat: "Smileys & Emotion" },
  { c: "🤪", n: "zany face", s: "zany_face", k: ["face", "silly", "goofy", "crazy", "bonkers"], t: false, cat: "Smileys & Emotion" },
  { c: "🤨", n: "face with raised eyebrow", s: "raised_eyebrow", k: ["face", "skeptical", "suspicious", "disapproval"], t: false, cat: "Smileys & Emotion" },
  { c: "🧐", n: "face with monocle", s: "monocle_face", k: ["face", "stuffy", "investigate", "distinguished", "smart"], t: false, cat: "Smileys & Emotion" },
  { c: "🤓", n: "nerd face", s: "nerd_face", k: ["face", "nerdy", "geek", "dork", "glasses", "smart"], t: false, cat: "Smileys & Emotion" },
  { c: "😎", n: "smiling face with sunglasses", s: "sunglasses", k: ["face", "cool", "smile", "summer", "beach", "sunglasses"], t: false, cat: "Smileys & Emotion" },
  { c: "🥳", n: "partying face", s: "partying_face", k: ["face", "celebration", "party", "hooray"], t: false, cat: "Smileys & Emotion" },
  { c: "😏", n: "smirking face", s: "smirk", k: ["face", "smug", "smirk", "sarcastic", "flirting"], t: false, cat: "Smileys & Emotion" },
  { c: "😒", n: "unamused face", s: "unamused", k: ["face", "indifference", "bored", "annoyed", "meh"], t: false, cat: "Smileys & Emotion" },
  { c: "😞", n: "disappointed face", s: "disappointed", k: ["face", "sad", "upset", "depressed"], t: false, cat: "Smileys & Emotion" },
  { c: "😔", n: "pensive face", s: "pensive", k: ["face", "sad", "depressed", "upset"], t: false, cat: "Smileys & Emotion" },
  { c: "😟", n: "worried face", s: "worried", k: ["face", "concern", "anxious"], t: false, cat: "Smileys & Emotion" },
  { c: "😕", n: "confused face", s: "confused", k: ["face", "puzzled", "confused", "dazed"], t: false, cat: "Smileys & Emotion" },
  { c: "🙁", n: "slightly frowning face", s: "slightly_frowning_face", k: ["face", "frowning", "disappointed", "sad", "upset"], t: false, cat: "Smileys & Emotion" },
  { c: "☹️", n: "frowning face", s: "frowning_face", k: ["face", "sad", "upset", "disappointed"], t: false, cat: "Smileys & Emotion" },
  { c: "😮", n: "face with open mouth", s: "open_mouth", k: ["face", "surprise", "impressed", "wow", "oh"], t: false, cat: "Smileys & Emotion" },
  { c: "😯", n: "hushed face", s: "hushed", k: ["face", "woo", "shhh"], t: false, cat: "Smileys & Emotion" },
  { c: "😲", n: "astonished face", s: "astonished", k: ["face", "xox", "surprised", "poisoned"], t: false, cat: "Smileys & Emotion" },
  { c: "😳", n: "flushed face", s: "flushed", k: ["face", "blush", "shy", "flattered"], t: false, cat: "Smileys & Emotion" },
  { c: "🥺", n: "pleading face", s: "pleading_face", k: ["face", "begging", "puppy", "eyes"], t: false, cat: "Smileys & Emotion" },
  { c: "😦", n: "frowning face with open mouth", s: "frowning", k: ["face", "aw", "what"], t: false, cat: "Smileys & Emotion" },
  { c: "😧", n: "anguished face", s: "anguished", k: ["face", "stunned", "nervous"], t: false, cat: "Smileys & Emotion" },
  { c: "😨", n: "fearful face", s: "fearful", k: ["face", "scared", "shocked", "oops", "fear"], t: false, cat: "Smileys & Emotion" },
  { c: "😥", n: "sad but relieved face", s: "disappointed_relieved", k: ["face", "phew", "sweat", "nervous"], t: false, cat: "Smileys & Emotion" },
  { c: "😢", n: "crying face", s: "cry", k: ["face", "tears", "sad", "depressed", "upset"], t: false, cat: "Smileys & Emotion" },
  { c: "😭", n: "loudly crying face", s: "sob", k: ["face", "cry", "tears", "sad", "bawling"], t: false, cat: "Smileys & Emotion" },
  { c: "😱", n: "face screaming in fear", s: "scream", k: ["face", "munch", "scream", "shocked", "terrified", "fear"], t: false, cat: "Smileys & Emotion" },
  { c: "😖", n: "confounded face", s: "confounded", k: ["face", "confused", "sick", "unwell", "oops"], t: false, cat: "Smileys & Emotion" },
  { c: "😣", n: "persevering face", s: "persevere", k: ["face", "sick", "no", "upset", "oops"], t: false, cat: "Smileys & Emotion" },
  { c: "😞", n: "disappointed face", s: "disappointed", k: ["face", "sad", "upset", "depressed"], t: false, cat: "Smileys & Emotion" },
  { c: "😓", n: "downcast face with sweat", s: "sweat", k: ["face", "hot", "sad", "tired", "exercise"], t: false, cat: "Smileys & Emotion" },
  { c: "😩", n: "weary face", s: "weary", k: ["face", "tired", "sleepy", "sad", "frustrated", "upset"], t: false, cat: "Smileys & Emotion" },
  { c: "😫", n: "tired face", s: "tired_face", k: ["face", "sick", "whine", "upset", "frustrated"], t: false, cat: "Smileys & Emotion" },
  { c: "🥱", n: "yawning face", s: "yawning_face", k: ["face", "tired", "sleepy", "bored"], t: false, cat: "Smileys & Emotion" },
  { c: "😤", n: "face with steam from nose", s: "triumph", k: ["face", "gas", "phew", "proud", "pride"], t: false, cat: "Smileys & Emotion" },
  { c: "😡", n: "pouting face", s: "rage", k: ["angry", "mad", "hate", "despise", "rage"], t: false, cat: "Smileys & Emotion" },
  { c: "😠", n: "angry face", s: "angry", k: ["mad", "face", "annoyed", "frustrated"], t: false, cat: "Smileys & Emotion" },
  { c: "🤬", n: "face with symbols on mouth", s: "cursing_face", k: ["face", "swearing", "cursing", "angry"], t: false, cat: "Smileys & Emotion" },
  { c: "😈", n: "smiling face with horns", s: "smiling_imp", k: ["devil", "horns", "evil", "impish"], t: false, cat: "Smileys & Emotion" },
  { c: "👿", n: "angry face with horns", s: "imp", k: ["devil", "angry", "evil", "imp"], t: false, cat: "Smileys & Emotion" },
  { c: "💀", n: "skull", s: "skull", k: ["dead", "death", "skeleton", "dying"], t: false, cat: "Smileys & Emotion" },
  { c: "💩", n: "pile of poo", s: "hankey", k: ["poop", "shit", "crap"], t: false, cat: "Smileys & Emotion" },
  { c: "🤡", n: "clown face", s: "clown_face", k: ["face", "clown", "circus"], t: false, cat: "Smileys & Emotion" },
  { c: "👹", n: "ogre", s: "japanese_ogre", k: ["monster", "demon", "ogre"], t: false, cat: "Smileys & Emotion" },
  { c: "👺", n: "goblin", s: "japanese_goblin", k: ["monster", "demon", "goblin"], t: false, cat: "Smileys & Emotion" },
  { c: "👻", n: "ghost", s: "ghost", k: ["halloween", "spooky", "boo"], t: false, cat: "Smileys & Emotion" },
  { c: "👽", n: "alien", s: "alien", k: ["ufo", "space", "extraterrestrial"], t: false, cat: "Smileys & Emotion" },
  { c: "👾", n: "alien monster", s: "space_invader", k: ["game", "arcade", "play"], t: false, cat: "Smileys & Emotion" },
  { c: "🤖", n: "robot", s: "robot", k: ["computer", "machine", "bot", "ai"], t: false, cat: "Smileys & Emotion" },
  { c: "❤️", n: "red heart", s: "heart", k: ["love", "like", "valentines"], t: false, cat: "Smileys & Emotion" },
  { c: "💔", n: "broken heart", s: "broken_heart", k: ["sad", "sorry", "break"], t: false, cat: "Smileys & Emotion" },
  { c: "💥", n: "collision", s: "boom", k: ["bomb", "explode", "explosion", "collision"], t: false, cat: "Smileys & Emotion" },
  { c: "💫", n: "dizzy", s: "dizzy", k: ["star", "sparkle", "shoot", "magic"], t: false, cat: "Smileys & Emotion" },
  { c: "💦", n: "sweat droplets", s: "sweat_drops", k: ["water", "drip", "oops"], t: false, cat: "Smileys & Emotion" },
  { c: "💨", n: "dashing away", s: "dash", k: ["wind", "air", "fast", "shoo", "fart", "smoke", "puff"], t: false, cat: "Smileys & Emotion" },
  // People & Body
  { c: "👋", n: "waving hand", s: "wave", k: ["hands", "gesture", "goodbye", "solong", "farewell", "hello", "hi"], t: true, cat: "People & Body" },
  { c: "🤚", n: "raised back of hand", s: "raised_back_of_hand", k: ["fingers", "raised", "backhand"], t: true, cat: "People & Body" },
  { c: "🖐️", n: "hand with fingers splayed", s: "hand_splayed", k: ["hand", "fingers", "palm"], t: true, cat: "People & Body" },
  { c: "✋", n: "raised hand", s: "raised_hand", k: ["fingers", "stop", "highfive", "palm"], t: true, cat: "People & Body" },
  { c: "🖖", n: "vulcan salute", s: "vulcan_salute", k: ["hand", "fingers", "spock", "star trek"], t: true, cat: "People & Body" },
  { c: "👌", n: "ok hand", s: "ok_hand", k: ["fingers", "limbs", "perfect", "ok", "okay"], t: true, cat: "People & Body" },
  { c: "🤌", n: "pinched fingers", s: "pinched_fingers", k: ["hand", "pinched", "italian", "sarcastic"], t: true, cat: "People & Body" },
  { c: "🤏", n: "pinching hand", s: "pinching_hand", k: ["hand", "small", "tiny"], t: true, cat: "People & Body" },
  { c: "✌️", n: "victory hand", s: "v", k: ["fingers", "ohyeah", "peace", "two"], t: true, cat: "People & Body" },
  { c: "🤞", n: "crossed fingers", s: "crossed_fingers", k: ["hand", "good", "lucky"], t: true, cat: "People & Body" },
  { c: "🤟", n: "love-you gesture", s: "love_you_gesture", k: ["hand", "ily", "love"], t: true, cat: "People & Body" },
  { c: "🤘", n: "sign of the horns", s: "metal", k: ["hand", "fingers", "rock", "metal"], t: true, cat: "People & Body" },
  { c: "🤙", n: "call me hand", s: "call_me_hand", k: ["hand", "shaka", "hang loose"], t: true, cat: "People & Body" },
  { c: "👈", n: "backhand index pointing left", s: "point_left", k: ["direction", "fingers", "hand", "left"], t: true, cat: "People & Body" },
  { c: "👉", n: "backhand index pointing right", s: "point_right", k: ["fingers", "hand", "direction", "right"], t: true, cat: "People & Body" },
  { c: "👆", n: "backhand index pointing up", s: "point_up_2", k: ["fingers", "hand", "direction", "up"], t: true, cat: "People & Body" },
  { c: "👇", n: "backhand index pointing down", s: "point_down", k: ["fingers", "hand", "direction", "down"], t: true, cat: "People & Body" },
  { c: "☝️", n: "index pointing up", s: "point_up", k: ["hand", "fingers", "direction", "up"], t: true, cat: "People & Body" },
  { c: "👍", n: "thumbs up", s: "thumbsup", k: ["yes", "awesome", "good", "agree", "accept", "cool", "hand", "like"], t: true, cat: "People & Body" },
  { c: "👎", n: "thumbs down", s: "thumbsdown", k: ["no", "dislike", "hand"], t: true, cat: "People & Body" },
  { c: "✊", n: "raised fist", s: "fist", k: ["fingers", "hand", "grasp", "power"], t: true, cat: "People & Body" },
  { c: "👊", n: "oncoming fist", s: "facepunch", k: ["angry", "violence", "fist", "hit", "attack", "hand"], t: true, cat: "People & Body" },
  { c: "🤝", n: "handshake", s: "handshake", k: ["agreement", "shake", "deal"], t: false, cat: "People & Body" },
  { c: "🙏", n: "folded hands", s: "pray", k: ["please", "hope", "wish", "namaste", "highfive", "hands", "pray"], t: true, cat: "People & Body" },
  { c: "✍️", n: "writing hand", s: "writing_hand", k: ["writing", "hand", "pen", "document"], t: true, cat: "People & Body" },
  { c: "💻", n: "laptop computer", s: "computer", k: ["laptop", "computer", "tech", "code", "dev"], t: false, cat: "Objects" },
  { c: "📱", n: "mobile phone", s: "iphone", k: ["phone", "mobile", "cell", "smartphone"], t: false, cat: "Objects" },
  { c: "🚀", n: "rocket", s: "rocket", k: ["launch", "ship", "space", "release", "deploy", "fast"], t: false, cat: "Travel & Places" },
  { c: "⚡", n: "high voltage", s: "zap", k: ["lightning", "fast", "energy", "power", "electric"], t: false, cat: "Travel & Places" },
  { c: "💡", n: "light bulb", s: "bulb", k: ["idea", "light", "thought"], t: false, cat: "Objects" },
  { c: "💰", n: "money bag", s: "moneybag", k: ["dollar", "payment", "coins", "sale", "cash"], t: false, cat: "Objects" },
  { c: "🔧", n: "wrench", s: "wrench", k: ["tool", "fix", "repair", "settings"], t: false, cat: "Objects" },
  { c: "🔨", n: "hammer", s: "hammer", k: ["tool", "build", "create", "fix"], t: false, cat: "Objects" },
  { c: "⚙️", n: "gear", s: "gear", k: ["settings", "config", "cog", "mechanical"], t: false, cat: "Objects" },
  { c: "🔗", n: "link", s: "link", k: ["rings", "url", "chain", "connection"], t: false, cat: "Objects" },
  { c: "📈", n: "chart increasing", s: "chart_with_upwards_trend", k: ["graph", "presentation", "stats", "recovery", "business", "economics", "money", "sales", "good"], t: false, cat: "Objects" },
  { c: "📉", n: "chart decreasing", s: "chart_with_downwards_trend", k: ["graph", "presentation", "stats", "recession", "business", "economics", "money", "sales", "bad"], t: false, cat: "Objects" },
  { c: "📊", n: "bar chart", s: "bar_chart", k: ["graph", "presentation", "stats", "data", "analytics"], t: false, cat: "Objects" },
  { c: "✅", n: "check mark button", s: "white_check_mark", k: ["ok", "agree", "confirm", "verified", "done", "check", "success"], t: false, cat: "Symbols" },
  { c: "❌", n: "cross mark", s: "x", k: ["no", "delete", "remove", "cancel", "wrong", "error", "fail"], t: false, cat: "Symbols" },
  { c: "⚠️", n: "warning", s: "warning", k: ["exclamation", "wip", "alert", "danger", "caution"], t: false, cat: "Symbols" },
  { c: "❓", n: "question mark", s: "question", k: ["doubt", "confused", "help"], t: false, cat: "Symbols" },
  { c: "❗", n: "exclamation mark", s: "exclamation", k: ["danger", "surprise", "wow", "warning"], t: false, cat: "Symbols" },
  { c: "🔄", n: "counterclockwise arrows button", s: "arrows_counterclockwise", k: ["sync", "cycle", "round", "repeat", "reload"], t: false, cat: "Symbols" },
  { c: "⏰", n: "alarm clock", s: "alarm_clock", k: ["time", "wake"], t: false, cat: "Objects" },
  { c: "🗑️", n: "wastebasket", s: "wastebasket", k: ["trash", "delete", "remove", "bin"], t: false, cat: "Objects" },
  { c: "🔀", n: "twisted rightwards arrows", s: "twisted_rightwards_arrows", k: ["merge", "branch", "git", "arrows", "combine"], t: false, cat: "Symbols" },
  { c: "📝", n: "memo", s: "memo", k: ["note", "write", "document", "text", "pencil"], t: false, cat: "Objects" },
  { c: "🔒", n: "locked", s: "lock", k: ["secure", "private", "closed", "security"], t: false, cat: "Objects" },
  { c: "🔓", n: "unlocked", s: "unlock", k: ["open", "public", "security"], t: false, cat: "Objects" },
  { c: "📌", n: "pushpin", s: "pushpin", k: ["location", "pin", "map"], t: false, cat: "Objects" },
  { c: "📚", n: "books", s: "books", k: ["library", "study", "reading", "documentation"], t: false, cat: "Objects" },
  { c: "💡", n: "light bulb", s: "bulb", k: ["idea", "suggestion", "light"], t: false, cat: "Objects" },
  { c: "💎", n: "gem stone", s: "gem", k: ["ruby", "diamond", "crystal", "valuable"], t: false, cat: "Objects" },
  { c: "💡", n: "light bulb", s: "bulb", k: ["light", "idea", "electric", "thought"], t: false, cat: "Objects" },
  { c: "💰", n: "money bag", s: "moneybag", k: ["dollar", "payment", "coins", "sale", "cash"], t: false, cat: "Objects" },
  { c: "🔧", n: "wrench", s: "wrench", k: ["tool", "fix", "settings", "spanner"], t: false, cat: "Objects" },
  { c: "🔨", n: "hammer", s: "hammer", k: ["tool", "build", "create", "fix"], t: false, cat: "Objects" },
  { c: "⚙️", n: "gear", s: "gear", k: ["settings", "config", "cog", "mechanical"], t: false, cat: "Objects" },
  { c: "🔗", n: "link", s: "link", k: ["rings", "url", "chain", "connection"], t: false, cat: "Objects" },
  { c: "📈", n: "chart increasing", s: "chart_with_upwards_trend", k: ["graph", "presentation", "stats", "recovery", "business", "economics", "money", "sales", "good"], t: false, cat: "Objects" },
  { c: "📉", n: "chart decreasing", s: "chart_with_downwards_trend", k: ["graph", "presentation", "stats", "recession", "business", "economics", "money", "sales", "bad"], t: false, cat: "Objects" },
  { c: "📊", n: "bar chart", s: "bar_chart", k: ["graph", "presentation", "stats", "data", "analytics"], t: false, cat: "Objects" },
  { c: "✅", n: "check mark button", s: "white_check_mark", k: ["ok", "agree", "confirm", "verified", "done", "check", "success"], t: false, cat: "Symbols" },
  { c: "❌", n: "cross mark", s: "x", k: ["no", "delete", "remove", "cancel", "wrong", "error", "fail"], t: false, cat: "Symbols" },
  { c: "⚠️", n: "warning", s: "warning", k: ["exclamation", "wip", "alert", "danger", "caution"], t: false, cat: "Symbols" },
  { c: "❓", n: "question mark", s: "question", k: ["doubt", "confused", "help"], t: false, cat: "Symbols" },
  { c: "❗", n: "exclamation mark", s: "exclamation", k: ["danger", "surprise", "wow", "warning"], t: false, cat: "Symbols" },
  { c: "🔄", n: "counterclockwise arrows button", s: "arrows_counterclockwise", k: ["sync", "cycle", "round", "repeat", "reload"], t: false, cat: "Symbols" },
  { c: "⏰", n: "alarm clock", s: "alarm_clock", k: ["time", "wake"], t: false, cat: "Objects" },
  { c: "🗑️", n: "wastebasket", s: "wastebasket", k: ["trash", "delete", "remove", "bin"], t: false, cat: "Objects" },
  { c: "🔀", n: "twisted rightwards arrows", s: "twisted_rightwards_arrows", k: ["merge", "branch", "git", "arrows", "combine"], t: false, cat: "Symbols" },
  { c: "📝", n: "memo", s: "memo", k: ["note", "write", "document", "text", "pencil"], t: false, cat: "Objects" },
  { c: "🔒", n: "locked", s: "lock", k: ["secure", "private", "closed", "security"], t: false, cat: "Objects" },
  { c: "🔓", n: "unlocked", s: "unlock", k: ["open", "public", "security"], t: false, cat: "Objects" },
  { c: "📌", n: "pushpin", s: "pushpin", k: ["location", "pin", "map"], t: false, cat: "Objects" },
  { c: "📚", n: "books", s: "books", k: ["library", "study", "reading", "documentation"], t: false, cat: "Objects" },
  { c: "💡", n: "light bulb", s: "bulb", k: ["idea", "suggestion", "light"], t: false, cat: "Objects" },
  { c: "💎", n: "gem stone", s: "gem", k: ["ruby", "diamond", "crystal", "valuable"], t: false, cat: "Objects" }
];

export const categories = [
  "All",
  "Smileys & Emotion",
  "People & Body",
  "Animals & Nature",
  "Food & Drink",
  "Travel & Places",
  "Activities",
  "Objects",
  "Symbols",
  "Flags"
];

// Skin tone modifiers
export const skinTones = [
  { name: "Default", modifier: "" },
  { name: "Light", modifier: "🏻" },
  { name: "Medium-Light", modifier: "🏼" },
  { name: "Medium", modifier: "🏽" },
  { name: "Medium-Dark", modifier: "🏾" },
  { name: "Dark", modifier: "🏿" }
];