const MIME_MAP: Record<string, string> = {
  zip: "application/zip",
  jar: "application/java-archive",
  war: "application/java-archive",
  ear: "application/java-archive",
  apk: "application/vnd.android.package-archive",
  ipa: "application/octet-stream",
  docx: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  xlsx: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  pptx: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  odt: "application/vnd.oasis.opendocument.text",
  ods: "application/vnd.oasis.opendocument.spreadsheet",
  odp: "application/vnd.oasis.opendocument.presentation",
  epub: "application/epub+zip",
  cbz: "application/x-cbz",
  xpi: "application/x-xpinstall",
  crx: "application/x-chrome-extension",
  txt: "text/plain",
  md: "text/markdown",
  html: "text/html",
  htm: "text/html",
  xml: "application/xml",
  json: "application/json",
  yaml: "application/x-yaml",
  yml: "application/x-yaml",
  toml: "application/toml",
  css: "text/css",
  js: "application/javascript",
  ts: "application/typescript",
  tsx: "application/typescript",
  jsx: "application/javascript",
  py: "text/x-python",
  java: "text/x-java-source",
  kt: "text/x-kotlin",
  go: "text/x-go",
  rs: "text/x-rustsrc",
  c: "text/x-c",
  cpp: "text/x-c++src",
  h: "text/x-c",
  hpp: "text/x-c++src",
  cs: "text/x-csharp",
  rb: "text/x-ruby",
  php: "application/x-php",
  swift: "text/x-swift",
  sh: "application/x-sh",
  bash: "application/x-sh",
  sql: "application/sql",
  ini: "text/plain",
  conf: "text/plain",
  cfg: "text/plain",
  log: "text/plain",
  csv: "text/csv",
  properties: "text/plain",
  env: "text/plain",
  gitignore: "text/plain",
  png: "image/png",
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  gif: "image/gif",
  webp: "image/webp",
  bmp: "image/bmp",
  ico: "image/x-icon",
  svg: "image/svg+xml",
  pdf: "application/pdf",
  class: "application/java-vm",
  dex: "application/vnd.android.dex",
};

export function mimeFromExtension(filename: string): string {
  const ext = filename.split(".").pop()?.toLowerCase() ?? "";
  return MIME_MAP[ext] ?? "application/octet-stream";
}

export function getExtension(filename: string): string {
  return filename.split(".").pop()?.toLowerCase() ?? "";
}
